### PR TITLE
Ft codeclimate circleci 187300136

### PR DESCRIPTION
**Pull request by Mukunzijames**
issue in referencing?
 Questions:
#### What does this PR do?

configuring circleci burges in readme and codeclimate.

 Description of Task to be completed?
- setting up circleci  and config.yml
- setting up coverall.io and coverage
How should this be manually tested?
- npm run dev
- npm run test
#### Any background context you want to provide?
-dummy data are provided before having the real data
#### What are the relevant pivotal tracker/Trello stories?
- id of the project
#187300135  
#187300134
#187300136

### CODE REVIEW

**Review by Ruthuwamahoro — APPROVED** [review]
Hello!Ruth here.You have done great job

**Review by RWEMAREMY — APPROVED** [review]
Good work

**Review by TuyishimireEric — APPROVED** [review]
# Status: APPROVED 🟢  
### Hi  @Mukunzijames   👋 👋 

#### I'm @TuyishimireEric,

Thank you for completing the following
- Integrated Coveralls code coverage service successfully🥇 
- Integrated CirlceCI with readme badge successfully🥇 


Your task is complete!  Congratulations! 🎉 

### Cheers and Happy coding!👏👏👏

**Review by fab-ryan — CHANGES_REQUESTED** [review]
Squash your commits it's more than 10 please make it 1 commit

**Pull request closed without merging**
